In [1]:
import cv2
import numpy as np

In [2]:
#contours are curves joining all the continuous points along the boundary which are having the same color or intensity
#useful for shape analysis, object detection and object recognition
#for better accuracy we are going to use binary image. Before finding the contour we are going to apply thresholding 
# and canny edge detection
img = cv2.imread('opencv.png')
img_gray = cv2.imread('opencv.png',0)

#apply threshold
ret,thresh = cv2.threshold(img_gray,159,255,cv2.THRESH_BINARY)

#the contours gives us two value, contours and hierarchy
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
#contours gives us a list of numpy array of (x,y) coordinate system
print('Number of Contours = '+str(len(contours)))
print(contours[2])

#now apply draw contours on original image to join all of them
cv2.drawContours(img, contours, -1, (107,25,100), 2)

cv2.imshow('OpenCV',img)
cv2.imshow('OpenCV Thresh', thresh)
cv2.imshow('OpenCV Gray',img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of Contours = 12
[[[ 73 208]]

 [[ 74 207]]

 [[ 75 207]]

 [[ 76 207]]

 [[ 77 207]]

 [[ 78 207]]

 [[ 79 207]]

 [[ 80 208]]

 [[ 81 209]]

 [[ 80 210]]

 [[ 79 210]]

 [[ 78 210]]

 [[ 77 210]]

 [[ 76 210]]

 [[ 75 210]]

 [[ 74 210]]

 [[ 73 210]]

 [[ 72 209]]]


### Self Practice

In [13]:
def nothing(x):
    pass

cv2.namedWindow('Image')
cv2.createTrackbar('Thresh Value', 'Image', 0,255, nothing)

while(True):
    img = cv2.imread('lane.jpg')
    img = cv2.resize(img,(700,500))
    
    th = cv2.getTrackbarPos('Thresh Value', 'Image')

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    _,th = cv2.threshold(gray, th, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(th, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

    cv2.drawContours(img, contours, -1, (150,20,150), 2)

    cv2.imshow('Image', img)
    if cv2.waitKey(1) & 0xFF == 27:
        break
cv2.destroyAllWindows()