In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
img = cv2.imread('shape.jpg')
#convert to gray image
imgg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#get the threshold
_, thresh = cv2.threshold(imgg, 240,255,cv2.THRESH_BINARY)
#find the contours
contours, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

for contour in contours:
    approx = cv2.approxPolyDP(contour, 0.01*cv2.arcLength(contour, True), True) #approxPolyDP find potential polygon
#in image. contour in the src, arclength measures the arclength of the contour. True means closed curve. 
#This return the number of polygonal curve
    cv2.drawContours(img, [approx], 0, (0,0,0), 2)
    print(approx)
    
    x = approx.ravel()[0] #get the co-ordinate of the shape where to write
    print(x)
    y = approx.ravel()[1]
    print(y)
    
    if len(approx) == 3:
        cv2.putText(img, 'Triangle', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
    elif len(approx) == 4:
        (x,y,w,h) = cv2.boundingRect(approx)
        aspect_ratio = float(w/h)
        if aspect_ratio>=9.5 and aspect_ratio<=1:
            cv2.putText(img, 'Square', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
        else:
            cv2.putText(img, 'Rectangle', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
    elif len(approx) == 5:
        cv2.putText(img, 'Pentagon', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
    elif len(approx) == 10:
        cv2.putText(img, 'Star', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
    else:
        cv2.putText(img, 'Circle', (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0,0,134), 2)
    
    
cv2.imshow('Shape',img)
cv2.imshow('Shape Gray',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0   0]]

 [[  0 469]]

 [[449 469]]

 [[449   0]]]
0
0
[[[324 468]]

 [[325 467]]

 [[326 468]]

 [[325 469]]]
324
468
[[[303 468]]

 [[304 467]]

 [[305 468]]

 [[304 469]]]
303
468
[[[270 468]]

 [[271 467]]

 [[272 468]]

 [[271 469]]]
270
468
[[[244 468]]

 [[245 467]]

 [[246 468]]

 [[245 469]]]
244
468
[[[224 468]]

 [[225 467]]

 [[226 468]]

 [[225 469]]]
224
468
[[[210 468]]

 [[211 467]]

 [[212 468]]

 [[211 469]]]
210
468
[[[200 468]]

 [[201 467]]

 [[202 468]]

 [[201 469]]]
200
468
[[[182 468]]

 [[183 467]]

 [[184 468]]

 [[183 469]]]
182
468
[[[176 468]]

 [[177 467]]

 [[178 468]]

 [[177 469]]]
176
468
[[[172 468]]

 [[173 467]]

 [[174 468]]

 [[173 469]]]
172
468
[[[165 468]]

 [[166 467]]

 [[167 468]]

 [[166 469]]]
165
468
[[[127 468]]

 [[128 467]]

 [[129 468]]

 [[128 469]]]
127
468
[[[110 468]]

 [[111 467]]

 [[112 468]]

 [[111 469]]]
110
468
[[[292 467]]

 [[293 466]]

 [[294 467]]

 [[293 468]]]
292
467
[[[231 467]]

 [[232 466]]

 [[233 467]]

 [

 [[402 348]]]
346
348
[[[387 388]]

 [[388 387]]

 [[389 388]]

 [[388 389]]]
387
388
[[[386 387]]

 [[387 386]]

 [[388 387]]

 [[387 388]]]
386
387
[[[384 385]]

 [[385 384]]

 [[386 384]]

 [[387 385]]

 [[387 386]]

 [[386 387]]

 [[385 387]]

 [[384 386]]]
384
385
[[[383 384]]

 [[384 383]]

 [[385 384]]

 [[384 385]]]
383
384
[[[382 383]]

 [[383 382]]

 [[384 383]]

 [[383 384]]]
382
383
[[[381 382]]

 [[382 381]]

 [[383 382]]

 [[382 383]]]
381
382
[[[380 381]]

 [[381 380]]

 [[382 381]]

 [[381 382]]]
380
381
[[[379 380]]

 [[380 379]]

 [[381 380]]

 [[380 381]]]
379
380
[[[378 379]]

 [[379 378]]

 [[380 379]]

 [[379 380]]]
378
379
[[[377 378]]

 [[378 377]]

 [[379 378]]

 [[378 379]]]
377
378
[[[376 377]]

 [[377 376]]

 [[378 377]]

 [[377 378]]]
376
377
[[[375 376]]

 [[376 375]]

 [[377 376]]

 [[376 377]]]
375
376
[[[374 375]]

 [[375 374]]

 [[376 375]]

 [[375 376]]]
374
375
[[[373 374]]

 [[374 373]]

 [[375 374]]

 [[374 375]]]
373
374
[[[372 373]]

 [[373 372]]

 [[268 207]]]
271
205
[[[271 209]]

 [[270 215]]

 [[267 215]]

 [[267 218]]

 [[270 219]]

 [[270 234]]

 [[273 239]]

 [[279 240]]

 [[282 239]]

 [[282 237]]

 [[276 236]]

 [[274 234]]

 [[274 219]]

 [[280 218]]

 [[280 215]]

 [[275 216]]

 [[274 209]]]
271
209
[[[158 207]]

 [[174 205]]

 [[181 208]]

 [[182 210]]

 [[177 217]]

 [[168 214]]

 [[163 219]]

 [[163 229]]

 [[166 233]]

 [[178 232]]

 [[180 239]]

 [[177 242]]

 [[162 242]]

 [[153 235]]

 [[153 214]]]
158
207
[[[162 209]]

 [[156 215]]

 [[156 233]]

 [[163 239]]

 [[175 239]]

 [[175 235]]

 [[168 237]]

 [[161 233]]

 [[160 216]]

 [[166 211]]

 [[173 211]]

 [[176 213]]

 [[177 210]]

 [[173 208]]]
162
209
[[[175 211]]

 [[176 210]]

 [[177 211]]

 [[176 212]]]
175
211
[[[ 41 206]]

 [[ 42 205]]

 [[ 43 206]]

 [[ 42 207]]]
41
206
[[[ 43 205]]

 [[ 44 204]]

 [[ 45 205]]

 [[ 44 206]]]
43
205
[[[ 46 202]]

 [[ 47 201]]

 [[ 48 202]]

 [[ 47 203]]]
46
202
[[[405 201]]

 [[406 200]]

 [[407 201]]

 [[406 202]]]
4

[[[46 47]]

 [[47 46]]

 [[48 47]]

 [[47 48]]]
46
47
[[[45 46]]

 [[46 45]]

 [[47 46]]

 [[46 47]]]
45
46
[[[345  44]]

 [[406  45]]

 [[404 108]]

 [[343 106]]]
345
44
[[[350  51]]

 [[350 100]]

 [[399 101]]

 [[399  52]]]
350
51
[[[353  96]]

 [[354  97]]

 [[352  99]]

 [[352 100]]

 [[351 101]]

 [[350 100]]

 [[350  98]]

 [[352  96]]]
353
96
[[[353  96]]

 [[354  95]]

 [[355  96]]

 [[354  97]]]
353
96
[[[359  90]]

 [[360  89]]

 [[361  90]]

 [[360  91]]]
359
90
[[[361  88]]

 [[362  87]]

 [[363  88]]

 [[362  89]]]
361
88
[[[367  82]]

 [[368  81]]

 [[369  82]]

 [[368  83]]]
367
82
[[[369  80]]

 [[370  79]]

 [[371  80]]

 [[370  81]]]
369
80
[[[375  74]]

 [[376  73]]

 [[377  74]]

 [[376  75]]]
375
74
[[[377  72]]

 [[378  71]]

 [[379  72]]

 [[378  73]]]
377
72
[[[383  66]]

 [[384  65]]

 [[385  66]]

 [[384  67]]]
383
66
[[[385  64]]

 [[386  63]]

 [[387  64]]

 [[386  65]]]
385
64
[[[391  58]]

 [[392  57]]

 [[393  58]]

 [[392  59]]]
391
58
[[[393  56]]

 [[

### Self Practice

In [15]:
img = cv2.imread('shape.jpg')
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_,th = cv2.threshold(img_gray, 20, 255, cv2.THRESH_BINARY)
contours,_ = cv2.findContours(th, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

for contour in contours:
    approx = cv2.approxPolyDP(contour, 0.001*cv2.arcLength(contour, True), True)
    cv2.drawContours(img, [approx], -1, (147,222,21), 2)
    
    x = approx.ravel()[0]
    y = approx.ravel()[1]
    font = cv2.FONT_HERSHEY_COMPLEX
    
    if len(approx) == 3:
        cv2.putText(img, 'Triangle', (x,y), font, 2, (0,0,255), 2)
    elif len(approx) == 5:
        cv2.putText(img, 'Pentagon', (x,y), font, 2, (0,0,255), 2)
    elif len(approx) == 4:
        (x,y,w,h) = cv2.boundingRect(approx)
        ratio = float(w/h)
        if ratio >=9.51 and ratio <=1:
            cv2.putText(img, 'Square', (x,y), font, 2, (0,0,255), 2)
        else:
            cv2.putText(img, 'Rectangle', (x,y), font, 2, (0,0,255), 2)
    else:
        cv2.putText(img, 'Circle', (x,y), font, 2, (0,0,255), 2)
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
    